# See example at https://github.com/bbatsov/rubocop/blob/master/config/default.yml
require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'Gemfile'
    - 'pivotal-to-trello.gemspec'

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 200

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Metrics/AbcSize:
  Enabled: true
  Max:     100

Metrics/BlockLength:
  Enabled:       false
  CountComments: false

Metrics/CyclomaticComplexity:
  Enabled: true
  Max:     15

Metrics/ClassLength:
  Enabled:       false
  CountComments: false

Metrics/MethodLength:
  Enabled:       true
  CountComments: false
  Max:           60

Metrics/PerceivedComplexity:
  Enabled: true
  Max:     20

Naming/BlockParameterName:
  MinNameLength: 1

Naming/FileName:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Style/AccessModifierDeclarations:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled:       true
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled:                   true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled:                   true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled:                   true
  EnforcedStyleForMultiline: comma
